/**
 * 
 * @copyright Copyright (c) 2017-2018 Gary Kim <gary@garykim.dev>
 * 
 * @author Gary Kim <gary@garykim.dev>
 *
 * @license GNU GPL version 3
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as 
 * published by the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 * 
 */

#pragma config(Motor,  port1,           portWheel,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           pointerMotor,  tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           starboardBowWheel, tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           starboardSternLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           portBowWheel,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           portSternLift, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           portMLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           starboardMLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           grabberMo,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          starboardWheel, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task auto()	{
	/*
	Psudeocode

	Turn Right for 500ms
	Grabber Open for 200ms and Lift Up for 2000ms
	MLift Down for 1000ms
	Move Forward for 3000ms
	MLift Up for 800ms
	Move Back for 2000ms
	Turn Left for 1000ms
	Move Forward for 3000ms

	Motor sets:

	driveRight
	motor[starboardDrive] =
	motor[starboardBowWheel] =

	driveLeft
	motor[portWheel] =
	motor[portBowWheel] =

	grabber
	motor[grabber] =

	mLift
	motor[portMLift] =
	motor[starboardMLift] =

	lift
	motor[starboardSternLift] =
	motor[portSternLift] =


	*/
	motor[starboardBowWheel] = 127;
	motor[starboardWheel] = 127;
	motor[portWheel] = 127;
	motor[portBowWheel] = 127;
	wait1Msec(150);
	motor[starboardWheel] = -127;
	motor[starboardBowWheel] = -127;
	motor[portWheel] = 127;
	motor[portBowWheel] = 127;
	wait1Msec(240);
	motor[starboardWheel] = 0;
	motor[starboardBowWheel] = 0;
	motor[portWheel] = 0;
	motor[portBowWheel] = 0;
	motor[grabberMo] =  -127;
	motor[starboardSternLift] = 50;
	motor[portSternLift] = 50;
	wait1Msec(200);
	motor[grabberMo] = 0;
	wait1Msec(1000);
	motor[starboardSternLift] = 0;
	motor[portSternLift] = 0;
	motor[starboardWheel] = 127;
	motor[starboardBowWheel] = 127;
	motor[portWheel] = 127;
	motor[portBowWheel] = 127;
	motor[portMLift] = -127;
	motor[starboardMLift] = -127;
	wait1Msec(500);
	motor[portMLift] = 0;
	motor[starboardMLift] = 0;
	wait1Msec(2500);
	motor[starboardWheel] = 0;
	motor[starboardBowWheel] = 0;
	motor[portWheel] = 0;
	motor[portBowWheel] = 0;
	motor[portMLift] = 127;
	motor[starboardMLift] = 127;
	wait1Msec(800);
	motor[starboardMLift] = 0;
	motor[portMLift] = 0;
	motor[starboardWheel] = -30;
	motor[starboardBowWheel] = -30;
	motor[portWheel] = -30;
	motor[portBowWheel] = -30;
	wait1Msec(100);
	motor[starboardWheel] = -50;
	motor[starboardBowWheel] = -50;
	motor[portWheel] = -50;
	motor[portBowWheel] = -50;
	wait1Msec(100);
	motor[starboardWheel] = -75;
	motor[starboardBowWheel] = -75;
	motor[portWheel] = -75;
	motor[portBowWheel] = -75;
	wait1Msec(100);
	motor[starboardWheel] = -100;
	motor[starboardBowWheel] = -100;
	motor[portWheel] = -100;
	motor[portBowWheel] = -100;
	wait1Msec(100);
	motor[starboardBowWheel] = -127;
	motor[starboardWheel] = -127;
	motor[portBowWheel] = -127;
	motor[portWheel] = -127;
	wait1Msec(1800);
	motor[starboardWheel] = 127;
	motor[starboardBowWheel] = 127;
	motor[portWheel] = -127;
	motor[portBowWheel] = -127;
	wait1Msec(1150);
	motor[starboardWheel] = 127;
	motor[starboardBowWheel] = 127;
	motor[portWheel] = 127;
	motor[portBowWheel] = 127;
	wait1Msec(1800);
	motor[portWheel] = -127;
	motor[portBowWheel] = -127;
	wait1Msec(300);
	motor[portWheel] = 127;
	motor[portBowWheel] = 127;
	wait1Msec(250);
	motor[starboardWheel] = 0;
	motor[starboardBowWheel] = 0;
	motor[portWheel] = 0;
	motor[portBowWheel] = 0;
}


task main()	{
	bool debug = false;
	int counter;
	int bowLift;
	int grabber;
	int portDrive;
	int starboardDrive;
	int mLift;
	bool special;
	int pointer;
	while(true)	{
		counter++;
		wait1Msec(10);
		if (!debug)	{
			//variable to motor
		//	motor[portBowLift] = bowLift;
			motor[portSternLift] = bowLift;
			motor[starboardSternLift] = bowLift;
			motor[starboardWheel] = starboardDrive;
			motor[starboardBowWheel] = starboardDrive;
			motor[portBowWheel] = portDrive;
			motor[portWheel] = portDrive;
			motor[grabberMo] = grabber;
			motor[pointerMotor] = pointer;
			special = false;

			//autoStart
			if(vexRT[Btn7L])	{
				startTask(auto);
				wait1Msec(15000);
			}

			//drive
			portDrive = vexRT[Ch1] + vexRT[Ch2];
			starboardDrive = - vexRT[Ch1] + vexRT[Ch2];

			//pointer
			if (vexRT[Btn7U])	{
				pointer = 127;
			}	else if (vexRT[Btn7R])	{
				pointer = -127;
			}	else {
				pointer = 0;
			}

			//grabber & mLift
			if(vexRT[Btn6U] && !vexRT[Btn6D])	{
					grabber = 45;
			} else if(vexRT[Btn6D] && !vexRT[Btn6U])	{
					grabber = -45;
			} else if (vexRT[Btn8D] && !vexRT[Btn6D] && !vexRT[Btn6U]){
					grabber = vexRT[Ch3];
			}	else if (vexRT[Btn6U] && vexRT[Btn6D]){
					grabber = 0;
					mLift = vexRT[Ch3];
					special = true;
			} else {
					grabber = 0;
			}

			//balancer
				if(vexRT[Btn8L])	{
						motor[starboardMLift] = vexRT[Ch4];
						motor[portMLift] = -1 * vexRT[Ch4];
				} else {
						motor[portMLift] = mLift;
						motor[starboardMLift] = mLift;
				}

			//lift
			if(vexRT[Btn5U])	{
					bowLift = 100;
			} else if(vexRT[Btn5D])	{
					grabber = -100;
			} else if(!vexRT[Btn8D] && !special){
					bowLift = vexRT[Ch3];
			}	else {
					bowLift = 10;
			}

			//debug toggle
			// Testing testing 123
		}
	}
}
